In [4]:
pip install promptbench



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install llmlingua


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [6]:
import promptbench as pb

/opt/homebrew/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
# print all supported datasets in promptbench
print('All supported datasets: ')
print(pb.SUPPORTED_DATASETS)

# load a dataset, sst2, for instance.
# if the dataset is not available locally, it will be downloaded automatically.
dataset_name = "gsm8k"
dataset = pb.DatasetLoader.load_dataset(dataset_name)

# print the first 5 examples
dataset[:5]

All supported datasets: 
['sst2', 'cola', 'qqp', 'mnli', 'mnli_matched', 'mnli_mismatched', 'qnli', 'wnli', 'rte', 'mrpc', 'mmlu', 'squad_v2', 'un_multi', 'iwslt2017', 'math', 'bool_logic', 'valid_parentheses', 'gsm8k', 'csqa', 'bigbench_date', 'bigbench_object_tracking', 'last_letter_concat', 'numersense', 'qasc', 'bbh', 'drop', 'arc-easy', 'arc-challenge']


[{'content': "Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?",
  'label': '18'},
 {'content': 'A robe takes 2 bolts of blue fiber and half that much white fiber.  How many bolts in total does it take?',
  'label': '3'},
 {'content': 'Josh decides to try flipping a house.  He buys a house for $80,000 and then puts in $50,000 in repairs.  This increased the value of the house by 150%.  How much profit did he make?',
  'label': '70000'},
 {'content': 'James decides to run 3 sprints 3 times a week.  He runs 60 meters each sprint.  How many total meters does he run a week?',
  'label': '540'},
 {'content': "Every day, Wendi feeds each of her chickens three cups of mixed chicken feed, containing seeds, mealworms and vegetables to help keep them healthy.  She giv

In [20]:
from llmlingua import PromptCompressor
llm_lingua = PromptCompressor(device_map="mps")

/opt/homebrew/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|██████████| 2/2 [00:33<00:00, 16.56s/it]


In [23]:
compressed_prompt = llm_lingua.compress_prompt(dataset[0]['content'], rate=0.33, force_tokens = ['\n', '?'])
print(compressed_prompt)

KeyboardInterrupt: 

In [25]:
prompt_teacher = '''[Rules]
- Choose from the options given the role that is more appropriate to solve the given situation.
- Don't add any additional explanation, just tell me the answer.
- If there is no suitable role, you must answer “none”.

[Options]
1. math teacher
2. history teacher

[Given Situation]
{user input}


[Example 1]
[User Input]
What is Newton’s law?
[Answer]
math teacher


[Example 2]
[User Input]
How did World War I end?
[Answer]
history teacher


[User Input]
'''
compressed_prompt_teacher = llm_lingua.compress_prompt(prompt_teacher, rate=0.3, target_token=80, force_tokens = ['\n', '?'])
print(compressed_prompt_teacher)

{'compressed_prompt': "[Rules]\n- Choose from the options given the role that is more appropriate to solve the given situation.\n- Don't add any additional explanation, just tell me the answer.\n- If there is no suitable role, you must answer “none”.\n\n[Options]\n1. math teacher\n2. history teacher\n\n[Given Situation]\n{user input}\n\n\n[Example 1]\n[User\nWhat is Newton’s law?\n[Answer]\nmath teacher\n\n\n[Example 2]\n[User Input]\nHow did World War I end?\n[Answer]\nhistory teacher\n\n\n[User Input]\n", 'origin_tokens': 117, 'compressed_tokens': 116, 'ratio': '1.0x', 'rate': '99.1%', 'saving': ', Saving $0.0 in GPT-4.'}


{'compressed_prompt': "[Rules]\n- Choose from the options given the role that is more appropriate to solve the given situation.\n- Don't add any additional explanation, just tell me the answer.\n- If there is no suitable role, you must answer “none”.\n\n[Options]\n1. math teacher\n2. history teacher\n\n[Given Situation]\n{user input}\n\n\n[Example 1]\n[User\nWhat is Newton’s law?\n[Answer]\nmath teacher\n\n\n[Example 2]\n[User Input]\nHow did World War I end?\n[Answer]\nhistory teacher\n\n\n[User Input]\n", 'origin_tokens': 117, 'compressed_tokens': 116, 'ratio': '1.0x', 'rate': '99.1%', 'saving': ', Saving $0.0 in GPT-4.'}